### ISSUE TITLE
(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius became +01:00 after 0.0.9 upgrade

### ISSUE THREAD

**Issue by wunderkopf** [jsakamoto/Toolbelt.Blazor.TimeZoneKit#1]
After upgrade to Blazor 0.0.9 UTC+02:00 became UTC+01:00. For example UTC time 20:00, before upgrade it was 22:00, after upgrade it is 21:00.
Using the following code:
TimeZoneInfo.ConvertTimeFromUtc(utcDateTime, TimeZoneInfo.Local).ToString("HH:mm");

**Comment by jsakamoto** [comment]
Could you tell me the time zone name in your browser?

```
Intl.DateTimeFormat().resolvedOptions().timeZone
```

![image](https://user-images.githubusercontent.com/95908/54242870-88c4eb00-4569-11e9-9940-ce20ef4250fd.png)

And also if you tell me that what is `Console.WriteLine(TimeZoneInfo.Local)` reported in your Blazor component, it is useful for me.

**Comment by wunderkopf** [comment]
JavaScript code prints: "Europe/Kiev" = $1
Blazor component with your library enabled: WASM: (UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius
Without your library: WASM: UTC

**Comment by jsakamoto** [comment]
I could not reproduce your problem.

![image](https://user-images.githubusercontent.com/95908/54279277-045d8100-45d8-11e9-90f6-e1a73a9b97c1.png)

```csharp
<h1>Toolbelt.Blazor.TimeZoneKit - Sample</h1>

<h2>Summary</h2>

<ul>
    <li>Number of TimeZonInfo is: @TimeZoneInfo.GetSystemTimeZones().Count</li>
    <li>TimeZoneInfo.Utc is @TimeZoneInfo.Utc</li>
    <li>TimeZoneInfo.Local is @TimeZoneInfo.Local</li>
    <li>DateTime.UtcNow is @DateTime.UtcNow</li>
    <li>DateTime.Now is @DateTime.Now</li>
    <li>Issue#1 is @(TimeZoneInfo.ConvertTimeFromUtc(utcDateTime, TimeZoneInfo.Local).ToString("HH:mm"))</li>
</ul>

<h2>All time zone list</h2>

<ul>
    @foreach (var timeZone in TimeZoneInfo.GetSystemTimeZones())
    {
        <li>@timeZone.Id</li>
    }
</ul>

@functions{
    DateTime utcDateTime = DateTime.UtcNow
}
```

Could you provide to me a minimum Blazor app project files as a Zip package which can reproduce your problem in your environment?

**Comment by wunderkopf** [comment]
It was my fail. I passed time without date to DateTime.Parse() function. And as result, because if daylight saving time, had incorrect records. Thanks for your help. Closing the issue.

**Comment by jsakamoto** [comment]
It was a good news because you could figured out and resolved the problem!
Thank you for your reporting.

Happy coding ;)
