### ISSUE TITLE
UseLocalTimeZone missing

### ISSUE THREAD

**Issue by americanslon** [jsakamoto/Toolbelt.Blazor.TimeZoneKit#4]
Hi,

I have upgraded to latest blazor preview and all of the sudden I get

`CS1929	'WebAssemblyHost' does not contain a definition for 'UseLocalTimeZone' and the best extension method overload 'TimeZoneKitExtension.UseLocalTimeZone(WebAssemblyHost)' requires a receiver of type 'WebAssemblyHost'	`

`using Toolbelt.Blazor.Extensions.DependencyInjection;` is included

Any ideas? I have been using this package for a couple of month with no issues.

**Comment by jsakamoto** [comment]
I have no idea. I could not reproduce your problem.

Sample program can build, and it works fine, on Blazor WebAssembly v.3.2 Preview 3.

https://github.com/jsakamoto/Toolbelt.Blazor.TimeZoneKit/blob/10f75aa526b851a7d135743b52bd9e822d539c92/Toolbelt.Blazor.TimeZoneKit.Sample/Program.cs#L18

Could you attach your project files to this issue?

**Comment by xdarkfirestorm** [comment]
Hi. I had the same issue. Did you migrate from an older version to the new preview? I fixed it by going through microsoft's migration guide. You have to uninstall many nuget packages and install other one's. This changes the namespace of the WebAssemblyHost and resolves the issue (did the trick for me).

[Migration doc](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/)

**Comment by chucker** [comment]
This is almost certainly due to the NuGet renaming. See the Migration doc above. Make sure you no longer reference any old packages; they will silently pull in the wrong assembly references.

**Comment by americanslon** [comment]
That was it. I somehow missed the whole upgrade guide. Thanks!

**Comment by jsakamoto** [comment]
Thank you for everyone to respond to this issue!

I'm appreciated for everyone's contributions 👍
